### ISSUE TITLE
free(): invalid pointer when using GetFuzzy()

### ISSUE THREAD

**Issue by persiyanov** [KeyviDev/keyvi#155]
- keyvi version: 0.4.1
- `terms.kv` file can be downloaded here https://gofile.io/d/0SMriP

Script to reproduce to problem:
```python
import numpy as np
import keyvi
from keyvi.dictionary import Dictionary 
from keyvi.compiler import CompletionDictionaryCompiler                                                                             

d = Dictionary('terms.kv')                                                                               
keys = list(d.GetAllKeys())                                                                                                         


while True: 
  key = np.random.choice(keys) 
  matches = list(d.GetFuzzy(key, 3)) 
  for m in matches: 
    m.GetMatchedString() 
    m.GetValue() 
```

For me, it exits after ~10 seconds with:
```
free(): invalid pointer
[1]    22023 abort (core dumped)  ipython
```

Let me know if there's anything else I could help with!

**Comment by persiyanov** [comment]
Tried it a few times more, getting different error messages:
```
python3.7: malloc.c:4009: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
[1]    7099 abort (core dumped)  ipython
```
or 
```
corrupted double-linked list
[1]    7767 abort (core dumped)  ipython
```
or
```
double free or corruption (out)
[1]    8110 abort (core dumped)  ipython
```


Then I started printing the `key` before the fail happens and it happens only for long keys. For example, it fails for me on `d.GetFuzzy('httpswwwbackcountrycomsramxx1eagle12speedchainskidsrm009zbks126lin', 3)`

**Comment by hendrikmuhs** [comment]
Thanks for the report!

I think you found a conceptual flaw: you created a completion dictionary which stores values as integers. The crash happens in `GetValue()` which tries to unpack the integer value as msgpack string - that's what keyvi uses for the json dictionary type - but in this case it shouldn't do that.

Will have another look tomorrow.

**Comment by hendrikmuhs** [comment]
I correct myself, its a stupid programming mistake introduced in https://github.com/KeyviDev/keyvi/pull/131: A buffer that is initialized with length 20 does not get resized.

Working on a fix.

**Comment by changun** [comment]
encountered the same problem as well. happy to share the dictionary file if that is helpful for testing.
