### ISSUE TITLE
How to use this library for C++

### ISSUE THREAD

**Issue by veronicabasso** [KeyviDev/keyvi#183]
Thanks for this awesome library.

I want to use the c_api of your library in my project. For example my sample code looks like this:
```
#include "keyvi/c_api/c_api.h"

...

auto* dict = keyvi_create_dictionary("/path/to/compiled.kv");
auto* match = keyvi_dictionary_get(dict, "my_key");
std::string val(keyvi_match_get_value_as_string(match));
cout << val;
```

However, this doesn't get compiled and gives error like unknown symbols. Could you please suggest how to compile and run this code?

**Comment by hendrikmuhs** [comment]
> I want to use the c_api of your library in my project. For example my sample code looks like this:

The issue says C++. Are you looking for C++ or C?
The `c_api` is mainly used for the Rust binding. I am not sure if it's intended to be a full API or just a bridge for the Rust binding, @narekgharibyan knows better than me.

If you look for C++, you should use the C++ heades directly, e.g. https://github.com/KeyviDev/keyvi/blob/master/keyvi/include/keyvi/dictionary/dictionary.h for the example above.

> However, this doesn't get compiled and gives error like unknown symbols. Could you please suggest how to compile and run this code?

keyvi is header-only, however you have to link the dependencies. To see what you have link, you can compile keyvi and take a look at `keyvi/flags`, right now it looks like this:

```
BUILD_TYPE=debug
KEYVI_CXX_FLAGS_ALL= -g -ggdb3 -msse4.2 -Wall -std=c++11
BOOST_LIBRARIES=program_options;iostreams;filesystem;system;regex;thread
ZLIB_LIBRARIES=/usr/lib/x86_64-linux-gnu/libz.so
KEYVI_COMPILE_DEFINITIONS=RAPIDJSON_HAS_STDSTRING
KEYVI_COMPILE_OPTIONS=-Wall
KEYVI_LINK_LIBRARIES_ALL= boost_program_options boost_iostreams boost_filesystem boost_system boost_regex boost_thread z snappy  tpie tiny-process-library
KEYVI_LINK_LIBRARIES_DYNAMIC= boost_program_options boost_iostreams boost_filesystem boost_system boost_regex boost_thread z snappy
KEYVI_LINK_LIBRARIES_STATIC= tpie tiny-process-library
KEYVI_LINK_FLAGS=
```

This is all quite rudimentary, sorry. Ideally a project that uses keyvi should use `cmake` and include keyvi as cmake modules, however I don't think this works at the moment. Are you using or plan to use cmake?

Our focus has been the python and rust libraries.

**Comment by veronicabasso** [comment]
Thanks for quick reply :-)

I am planning to use it for C++, and I use `cmake` for my project. I will try to link the required dependencies to see if it works.

**Comment by hendrikmuhs** [comment]
ok, great.

Another resource for cmake and keyvi usage in C++ is keyvi-server:

https://github.com/KeyviDev/keyvi-server/blob/master/CMakeLists.txt

**Comment by narekgharibyan** [comment]
>The c_api is mainly used for the Rust binding. I am not sure if it's intended to be a full API or just a bridge for the Rust binding, @narekgharibyan knows better than me.

Just to follow-up here, at the moment `c_api` doesn't provide full API, but rather is just a bridge for Rust bindings.

**Comment by veronicabasso** [comment]
Thanks @hendrikmuhs
