### ISSUE TITLE
Fetch all the keys with a specific length

### ISSUE THREAD

**Issue by vsraptor** [KeyviDev/keyvi#233]
Because keyvi is based on FST It should be possible to be able to get the key-value pairs based on the length of the key irregardless of the content.

This with the capability to store sequences : https://gist.github.com/vsraptor/8beb0c04fe5914c50d6d307393b34893

opens many new areas of use..

**Describe the solution you'd like**

kmatch = keyvi.index.get_keys_by_len(5)
[ k for k in kmatch ]

kvmatch = keyvi.index.get_kv_by_len(5)
{ k:v for k,v in kvmatch }

**Comment by hendrikmuhs** [comment]
> Because keyvi is based on FST It should be possible to be able to get the key-value pairs based on the length of the key irregardless of the content.

Yes, that shouldn't be a problem. For users of C++ this isn't hard to achieve given the existing traversers, for python this requires some plumbing.
