### ISSUE TITLE
Fuzzy match produces wrong results

### ISSUE THREAD

**Issue by illegalplumbing** [KeyviDev/keyvi#244]
Erroneous matches produced by GetFuzzy() when the prefix length equals the length of the key string in the index.
For example, the dictionary 
{"a": 1, "apple": 2}
GetFuzzy("app", 0, 1) would match "a"->1 with the score "0.0", and GetMatchedString() would return "app"

to reproduce execute the code in the attached file below

expected behavior:
 the query should return and empty result set

[keyvi_bug_20211217.py.zip](https://github.com/KeyviDev/keyvi/files/7737226/keyvi_bug_20211217.py.zip)

**Comment by hendrikmuhs** [comment]
thanks for the report and the detailed reproduction steps. I haven't found the time yet to look into it, but I will asap.
