### ISSUE TITLE
Fuzzy completion doesn't return all expected results

### ISSUE THREAD

**Issue by narekgharibyan** [KeyviDev/keyvi#50]
@hendrikmuhs as you've asked, opening an issue for FuzzyCompletions with some examples of not returning an expected results.

Input data:
```
# -*- coding: utf-8 -*-


import keyvi

c = keyvi.CompletionDictionaryCompiler({"memory_limit_mb": "10"})
c.Add("turkei news", 23698)
c.Add("turkei side", 18838)
c.Add("turkei urlaub", 23424)
c.Add("turkisch anfänger", 20788)
c.Add("turkisch für", 21655)
c.Add("turkisch für anfänger", 20735)
c.Add("turkçe dublaj", 28575)
c.Add("turkçe dublaj izle", 16391)
c.Add("turkçe izle", 19946)
c.Add("tuv akademie", 9557)
c.Add("tuv hessen", 7744)
c.Add("tuv i", 331)
c.Add("tuv in", 10188)
c.Add("tuv ib", 10189)
c.Add("tuv kosten", 11387)
c.Add("tuv nord", 46052)
c.Add("tuv sood", 46057)
c.Add("tus rhein", 462)
c.Add("tus rheinland", 39131)
c.Add("tus öffnungszeiten", 15999)

c.Compile()
c.WriteToFile('fuzzy.kv')

d = keyvi.Dictionary('fuzzy.kv')
c = keyvi.PrefixCompletion(d)

```

This returns an empty iterator: expected to see everything starting with `tuv`
```
for m in c.GetFuzzyCompletions('tuv', 0):
    print m.GetMatchedString()
```
This returns only `tus rhein`: expected to have `tus rheinland` as well.
```
for m in c.GetFuzzyCompletions('tuv rhein', 1):
    print m.GetMatchedString()
```
This returns an empty iterator: expected to see everything starting with `turkçe`
```
for m in c.GetFuzzyCompletions('turkçe', 1):
    print m.GetMatchedString()
```

**Comment by hendrikmuhs** [comment]
I verified this bug:

So far I see that once the length of the query is exceeded the score still gets calculated which is wrong for the completion case, it should calculate the edit distance up to the length of the query and then change into completion mode. 

Just a 1st look at the bug, requires some more thought to fix it.

**Comment by narekgharibyan** [comment]
Maybe it will be possible to derive from `FuzzyMatch`, and once there is a match, create another `CodePointStateTraverser` to traverse whole subtree for completions.
